"""Create users and rider sessions tables

Revision ID: 3d33c4a61e50
Revises: 
Create Date: 2026-09-09 03:09:57.327299
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '3d33c4a61e50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rider_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_mileage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('end_mileage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('gross_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_rider_sessions_status'),
    sa.CheckConstraint('fuel_cost >= 0', name='ck_rider_sessions_fuel_cost_non_negative'),
    sa.CheckConstraint('gross_income >= 0', name='ck_rider_sessions_gross_income_non_negative'),
    sa.CheckConstraint('other_expenses >= 0', name='ck_rider_sessions_other_expenses_non_negative'),
    sa.CheckConstraint('total_orders >= 0', name='ck_rider_sessions_total_orders_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_sessions_platform'), 'rider_sessions', ['platform'], unique=False)
    op.create_index(op.f('ix_rider_sessions_session_date'), 'rider_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_rider_sessions_status'), 'rider_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_rider_sessions_user_id'), 'rider_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rider_sessions_user_id'), table_name='rider_sessions')
    op.drop_index(op.f('ix_rider_sessions_status'), table_name='rider_sessions')
    op.drop_index(op.f('ix_rider_sessions_session_date'), table_name='rider_sessions')
    op.drop_index(op.f('ix_rider_sessions_platform'), table_name='rider_sessions')
    op.drop_table('rider_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###